FROM docker.io/fedora

MAINTAINER contact@primhillcomputers.com

################################# Executables:

################################# Dependencies by program type
# Dependencies: Binary programs
# Package installations:

# Non-packaged executable files copies:
# Origin file does not exist:/etc/ld.so.cache
# Origin file does not exist:/usr/lib64/gconv/ISO8859-1.so
# Origin file does not exist:/usr/lib64/libaudit.so.1.0.0
# Origin file does not exist:/usr/lib64/libblkid.so.1.1.0
# Origin file does not exist:/usr/lib64/libc-2.25.so
# Origin file does not exist:/usr/lib64/libcap-ng.so.0.0.0
# Origin file does not exist:/usr/lib64/libcrypt-nss-2.25.so
# Origin file does not exist:/usr/lib64/libcryptsetup.so.4.7.0
# Origin file does not exist:/usr/lib64/libdevmapper.so.1.02
# Origin file does not exist:/usr/lib64/libdl-2.25.so
# Origin file does not exist:/usr/lib64/libfreebl3.so
# Origin file does not exist:/usr/lib64/libfreeblpriv3.so
# Origin file does not exist:/usr/lib64/libgcrypt.so.20.1.7
# Origin file does not exist:/usr/lib64/libgpg-error.so.0.20.0
# Origin file does not exist:/usr/lib64/libidn.so.11.6.16
# Origin file does not exist:/usr/lib64/liblz4.so.1.7.5
# Origin file does not exist:/usr/lib64/liblzma.so.5.2.3
# Origin file does not exist:/usr/lib64/libnspr4.so
# Origin file does not exist:/usr/lib64/libnss_files-2.25.so
# Origin file does not exist:/usr/lib64/libnss_sss.so.2
# Origin file does not exist:/usr/lib64/libpam_misc.so.0.82.1
# Origin file does not exist:/usr/lib64/libpcre.so.1.2.8
# Origin file does not exist:/usr/lib64/libpthread-2.25.so
# Origin file does not exist:/usr/lib64/libseccomp.so.2.3.2
# Origin file does not exist:/usr/lib64/libselinux.so.1
# Origin file does not exist:/usr/lib64/libsepol.so.1
# Origin file does not exist:/usr/lib64/libsystemd.so.0.18.0
# Origin file does not exist:/usr/lib64/libudev.so.1.6.6
# Origin file does not exist:/usr/lib64/libuuid.so.1.3.0
# Origin file does not exist:/usr/lib64/security/pam_deny.so
# Origin file does not exist:/usr/lib64/security/pam_env.so
# Origin file does not exist:/usr/lib64/security/pam_faildelay.so
# Origin file does not exist:/usr/lib64/security/pam_keyinit.so
# Origin file does not exist:/usr/lib64/security/pam_limits.so
# Origin file does not exist:/usr/lib64/security/pam_listfile.so
# Origin file does not exist:/usr/lib64/security/pam_localuser.so
# Origin file does not exist:/usr/lib64/security/pam_loginuid.so
# Origin file does not exist:/usr/lib64/security/pam_permit.so
# Origin file does not exist:/usr/lib64/security/pam_shells.so
# Origin file does not exist:/usr/lib64/security/pam_succeed_if.so
# Origin file does not exist:/usr/lib64/security/pam_systemd.so
# Origin file does not exist:/usr/lib64/security/pam_unix.so
# Origin file does not exist:UNIX:[3646855,"/run/proftpd/proftpd.sock"]

# Data packages:

# Data files:
# Origin file does not exist:/home/rchateau/survol/Experimental/RetroBatch/Invalid device
# Origin file does not exist:/home/rchateau/survol/Icons.16x16
# Origin file does not exist:/home/rchateau/survol/Icons.16x16/fileicons.chromefans.org
# Origin file does not exist:/home/rchateau/survol/docs/github_wiki
# Origin file does not exist:/home/rchateau/survol/survol
# Origin file does not exist:/home/rchateau/survol/survol/sources_types
# Origin file does not exist:/home/rchateau/survol/survol/www
# Origin file does not exist:/usr/lib64/gconv/gconv-modules.cache
# Origin file does not exist:/usr/lib64/libfreeblpriv3.chk
# Origin file does not exist:/var/lib/sss/mc/group
# Origin file does not exist:/var/lib/sss/mc/initgroups
# Origin file does not exist:/var/lib/sss/mc/passwd

WORKDIR /home/rchateau/survol/Experimental/RetroBatch

# Port numbers:
# Unknown service number: 63707
EXPOSE 63707
# Unknown service number: 63703
EXPOSE 63703
# Unknown service number: 63706
EXPOSE 63706
# Unknown service number: 63710
EXPOSE 63710
# Unknown service number: 63708
EXPOSE 63708
# Unknown service number: 63705
EXPOSE 63705
# Unknown service number: 63711
EXPOSE 63711


# Processes tree
# 2018-05-08 14:09:40.614998 -> 2018-05-08 14:11:05.011156 :      *Unknown-command*
# 2018-05-08 00:00:00.000000 -> 2018-05-08 14:09:56.110693 :          *Unknown-command*
# 2018-05-08 14:09:54.652742 -> 2018-05-08 14:11:04.807936 :          *Unknown-command*
# 2018-05-08 14:09:55.193865 -> 2018-05-08 14:09:55.245535 :              /usr/sbin/unix_chkpwd rchateau nullok
# 2018-05-08 14:09:55.247514 -> 2018-05-08 14:09:55.678238 :              /usr/sbin/unix_chkpwd rchateau nullok
# 2018-05-08 14:09:55.685465 -> 2018-05-08 14:09:56.136965 :              /usr/sbin/unix_chkpwd rchateau chkexpiry

