FROM docker.io/fedora

MAINTAINER contact@primhillcomputers.com

################################# Executables:

################################# Dependencies by program type
# Dependencies: Binary programs
# Package installations:

# Non-packaged executable files copies:
# Origin file does not exist:/etc/ld.so.cache
# Origin file does not exist:/usr/lib64/libacl.so.1.1.0
# Origin file does not exist:/usr/lib64/libattr.so.1.1.0
# Origin file does not exist:/usr/lib64/libbz2.so.1.0.6
# Origin file does not exist:/usr/lib64/libc-2.21.so
# Origin file does not exist:/usr/lib64/libcap.so.2.24
# Origin file does not exist:/usr/lib64/libdl-2.21.so
# Origin file does not exist:/usr/lib64/libdw-0.166.so
# Origin file does not exist:/usr/lib64/libelf-0.166.so
# Origin file does not exist:/usr/lib64/libgcc_s-5.3.1-20160406.so.1
# Origin file does not exist:/usr/lib64/libgcrypt.so.20.0.3
# Origin file does not exist:/usr/lib64/libgpg-error.so.0.17.0
# Origin file does not exist:/usr/lib64/liblzma.so.5.2.0
# Origin file does not exist:/usr/lib64/libm-2.21.so
# Origin file does not exist:/usr/lib64/libnss_files-2.21.so
# Origin file does not exist:/usr/lib64/libpcre.so.1.2.7
# Origin file does not exist:/usr/lib64/libprocps.so.4.0.0
# Origin file does not exist:/usr/lib64/libpthread-2.21.so
# Origin file does not exist:/usr/lib64/libresolv-2.21.so
# Origin file does not exist:/usr/lib64/librt-2.21.so
# Origin file does not exist:/usr/lib64/libselinux.so.1
# Origin file does not exist:/usr/lib64/libsystemd.so.0.6.0
# Origin file does not exist:/usr/lib64/libtinfo.so.5.9
# Origin file does not exist:/usr/lib64/libz.so.1.2.8

# Data packages:

# Data files:
# Origin file does not exist:/home/rchateau/rdfmon-code/Experimental/RetroBatch
# Origin file does not exist:/home/rchateau/rdfmon-code/Experimental/RetroBatch/TestProgs/sample_shell.sh
# Origin file does not exist:/home/rchateau/rdfmon-code/Experimental/RetroBatch/UnknownFileDescr:3
# Origin file does not exist:/home/rchateau/rdfmon-code/Experimental/RetroBatch/UnknownFileDescr:4
# Origin file does not exist:/usr/lib/locale/locale-archive
# Origin file does not exist:/usr/lib64/gconv/gconv-modules.cache

WORKDIR /home/rchateau/rdfmon-code/Experimental/RetroBatch
CMD [ "bash","TestProgs/sample_she..." ]
WORKDIR /home/rchateau/rdfmon-code/Experimental/RetroBatch


# Processes tree
# 2018-05-20 08:26:47.177594 -> 2018-05-20 08:26:47.553096 :      bash TestProgs/sample_she...
# 2018-05-20 08:26:47.185552 -> 2018-05-20 08:26:47.553096 :          ls
# 2018-05-20 08:26:47.198399 -> 2018-05-20 08:26:47.553096 :          ps -ef
# 2018-05-20 08:26:47.545561 -> 2018-05-20 08:26:47.553096 :          cat TestProgs/sample_she...
# 2018-05-20 08:26:47.185933 -> 2018-05-20 08:26:47.553096 :      *Unknown-command*
# 2018-05-20 08:26:47.199213 -> 2018-05-20 08:26:47.543412 :          wc

