FROM docker.io/fedora

MAINTAINER contact@primhillcomputers.com

################################# Executables:

################################# Dependencies by program type
# Dependencies: Binary programs
# Package installations:

# Non-packaged executable files copies:
# Origin file does not exist:/etc/ld.so.cache
# Origin file does not exist:/usr/lib64/libc-2.21.so
# Origin file does not exist:/usr/lib64/libcom_err.so.2.1
# Origin file does not exist:/usr/lib64/libcrypto.so.1.0.1k
# Origin file does not exist:/usr/lib64/libdl-2.21.so
# Origin file does not exist:/usr/lib64/libexpat.so.1.6.0
# Origin file does not exist:/usr/lib64/libgcc_s-5.3.1-20160406.so.1
# Origin file does not exist:/usr/lib64/libgssapi_krb5.so.2.2
# Origin file does not exist:/usr/lib64/libicudata.so.54.1
# Origin file does not exist:/usr/lib64/libicuuc.so.54.1
# Origin file does not exist:/usr/lib64/libidn.so.11.6.15
# Origin file does not exist:/usr/lib64/libk5crypto.so.3.1
# Origin file does not exist:/usr/lib64/libkeyutils.so.1.5
# Origin file does not exist:/usr/lib64/libkrb5.so.3.3
# Origin file does not exist:/usr/lib64/libkrb5support.so.0.1
# Origin file does not exist:/usr/lib64/libm-2.21.so
# Origin file does not exist:/usr/lib64/libmetalink.so.3.0.0
# Origin file does not exist:/usr/lib64/libnss_dns-2.21.so
# Origin file does not exist:/usr/lib64/libnss_files-2.21.so
# Origin file does not exist:/usr/lib64/libnss_mdns4_minimal.so.2
# Origin file does not exist:/usr/lib64/libpcre.so.1.2.7
# Origin file does not exist:/usr/lib64/libpsl.so.0.2.4
# Origin file does not exist:/usr/lib64/libpthread-2.21.so
# Origin file does not exist:/usr/lib64/libresolv-2.21.so
# Origin file does not exist:/usr/lib64/libselinux.so.1
# Origin file does not exist:/usr/lib64/libssl.so.1.0.1k
# Origin file does not exist:/usr/lib64/libstdc++.so.6.0.21
# Origin file does not exist:/usr/lib64/libtinfo.so.5.9
# Origin file does not exist:/usr/lib64/libuuid.so.1.3.0
# Origin file does not exist:/usr/lib64/libz.so.1.2.8

# Data packages:

# Data files:
# Origin file does not exist:/home/rchateau/.wget-hsts
# Origin file does not exist:/home/rchateau/rdfmon-code/Experimental/RetroBatch/TestProgs/test_wget_hotmail.sh
# Origin file does not exist:/usr/lib/locale/locale-archive
# Origin file does not exist:/usr/lib64/gconv/gconv-modules.cache

WORKDIR /home/rchateau/survol/Experimental/RetroBatch
CMD [ "TestProgs/test_wget_..." ]

# Port numbers:
# Service: http
EXPOSE 80
# Service: https
EXPOSE 443


# Processes tree
# 2018-05-08 10:07:39.258934 -> 2018-05-08 10:07:39.571984 :      TestProgs/test_wget_...
# 2018-05-08 10:07:39.263696 -> 2018-05-08 10:07:39.571703 :          wget -P /tmp -r hotmail.com

