# Directory C:\Users\rchateau\Developpement\ReverseEngineeringApps\PythonStyle\tests\dockit_output_files\sample_shell_ltrace_tst_docker.docker

FROM docker.io/fedora

MAINTAINER contact@primhillcomputers.com

################################# Executables:

################################# Dependencies by program type
# Dependencies: Binary programs
# Package installations:

# Non-packaged executable files copies:
# Origin file does not exist:/etc/ld.so.cache
# Origin file does not exist:/lib64/libacl.so.1
# Origin file does not exist:/lib64/libattr.so.1
# Origin file does not exist:/lib64/libbz2.so.1
# Origin file does not exist:/lib64/libc.so.6
# Origin file does not exist:/lib64/libcap.so.2
# Origin file does not exist:/lib64/libdl.so.2
# Origin file does not exist:/lib64/libdw.so.1
# Origin file does not exist:/lib64/libelf.so.1
# Origin file does not exist:/lib64/libgcc_s.so.1
# Origin file does not exist:/lib64/libgcrypt.so.20
# Origin file does not exist:/lib64/libgpg-error.so.0
# Origin file does not exist:/lib64/liblzma.so.5
# Origin file does not exist:/lib64/libm.so.6
# Origin file does not exist:/lib64/libnss_files.so.2
# Origin file does not exist:/lib64/libpcre.so.1
# Origin file does not exist:/lib64/libprocps.so.4
# Origin file does not exist:/lib64/libpthread.so.0
# Origin file does not exist:/lib64/libresolv.so.2
# Origin file does not exist:/lib64/librt.so.1
# Origin file does not exist:/lib64/libselinux.so.1
# Origin file does not exist:/lib64/libsystemd.so.0
# Origin file does not exist:/lib64/libtinfo.so.5
# Origin file does not exist:/lib64/libz.so.1

# Data packages:

# Data files:
# Origin file does not exist:/home/rchateau/rdfmon-code/Experimental/RetroBatch/TestProgs/sample_shell.sh
# Origin file does not exist:/home/rchateau/rdfmon-code/Experimental/RetroBatch/UnknownFileDescr:255
# Origin file does not exist:/home/rchateau/rdfmon-code/Experimental/RetroBatch/UnknownFileDescr:4
# Origin file does not exist:/usr/lib/locale/locale-archive
# Origin file does not exist:/usr/lib64/gconv/gconv-modules.cache

WORKDIR /home/rchateau/rdfmon-code/Experimental/RetroBatch

ENV I_WANT_A_BROKEN_PS ""
ENV QUOTING_STYLE ""
ENV POSIX2 ""
ENV POSIXLY_CORRECT ""
ENV BLOCKSIZE ""
ENV LS_BLOCK_SIZE ""
ENV CMD_ENV ""
ENV LINES ""
ENV UNIX95 ""
ENV TABSIZE ""
ENV PS_PERSONALITY ""
ENV BLOCK_SIZE ""
ENV COLUMNS ""

# Processes tree
# 2018-05-20 09:00:22.529684 -> 2018-05-20 09:00:23.657686 :      *Unknown-command*
# 2018-05-20 09:00:22.557771 -> 2018-05-20 09:00:23.657686 :          /usr/bin/ls
# 2018-05-20 09:00:22.598022 -> 2018-05-20 09:00:23.657686 :          *Unknown-command*
# 2018-05-20 09:00:22.599853 -> 2018-05-20 09:00:23.631763 :          *Unknown-command*
# 2018-05-20 09:00:23.641969 -> 2018-05-20 09:00:23.657686 :          /usr/bin/cat

