#!/usr/bin/python

import os
import cgi
import sys
import rdflib
import urllib
import lib_common

import xml

arguments = cgi.FieldStorage()
try:
	rdfurl = arguments["url"].value
except KeyError:
	# For command line testing.
	# rdfurl = "http://127.0.0.1/PythonStyle/htbin/sources/cgi_sockets.py"
	rdfurl = "http://127.0.0.1/~rchateau/RevPython/htbin/sources/cgi_sockets.py"
	# rdfurl ="D:\\Projects\\Divers\\Reverse\\PythonStyle\\cgi_sockets.rdf"
	# rdfurl = "/home/rchateau/Developpement/ReverseEngineeringApps/PythonStyle/cgi_sockets.rdf"

grph = rdflib.Graph()
lib_common.Url2Grph( grph, rdfurl )
# TODO: Sets the right page title.
page_title = "Generated by Rdf2Html"
lib_common.Grph2Html( page_title, "", False, {}, grph )


